### ISSUE TITLE
:clipboard: **Milestone 1 todo:**

### ISSUE THREAD

**Issue by VojislavM** [edgeimpulse/example-standalone-inferencing-zephyr#21]
- [x] fix current build warnings
- [x] optimize cmake file  

:question: python build or CLI  (standard west commands)
:question: NUS service (UART BLE)  (in firmware application, not here)
- [x] test other models  

:question: position of `porting` files (in the root of the repo, exclude from sdk)
- [x] documentation - to repository
- [x] speed optimization
